[package]
name = "wasi-faster-dirent-count"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = []
date = []

[[example]]
name = "count-366-days"
required-features = ["date"]
